"""Repository protocols — abstract interfaces for all data access.

Extends the existing protocols (RunRepositoryProtocol, ApiKeysRepositoryProtocol,
HuntflowRepositoryProtocol) with new domain entity protocols.
"""

from __future__ import annotations

from typing import Any, Protocol

from app.domain.finding import Finding, FindingStatus
from app.domain.hunt import Hunt
from app.domain.session import Session
from app.domain.target import TargetBase
from app.domain.user import User
from app.domain.workspace import Workspace
from app.domain.report import Report


class UserRepositoryProtocol(Protocol):
    def create(self, user: User) -> None: ...
    def get(self, user_id: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def update(self, user_id: str, updates: dict[str, Any]) -> None: ...
    def delete(self, user_id: str) -> bool: ...


class WorkspaceRepositoryProtocol(Protocol):
    def create(self, workspace: Workspace) -> None: ...
    def get(self, workspace_id: str) -> Workspace | None: ...
    def list_all(self) -> list[Workspace]: ...
    def list_for_user(self, user_id: str) -> list[Workspace]: ...
    def update(self, workspace_id: str, updates: dict[str, Any]) -> None: ...
    def delete(self, workspace_id: str) -> bool: ...


class SessionRepositoryProtocol(Protocol):
    def create(self, session: Session) -> None: ...
    def get(self, session_id: str) -> Session | None: ...
    def list_all(self) -> list[Session]: ...
    def list_for_workspace(self, workspace_id: str) -> list[Session]: ...
    def update(self, session_id: str, updates: dict[str, Any]) -> None: ...
    def delete(self, session_id: str) -> bool: ...


class TargetRepositoryProtocol(Protocol):
    def create(self, target: TargetBase) -> None: ...
    def get(self, target_id: str) -> TargetBase | None: ...
    def list_all(self) -> list[TargetBase]: ...
    def list_for_session(self, session_id: str) -> list[TargetBase]: ...
    def update(self, target_id: str, updates: dict[str, Any]) -> None: ...
    def delete(self, target_id: str) -> bool: ...


class HuntRepositoryProtocol(Protocol):
    def create(self, hunt: Hunt) -> None: ...
    def get(self, hunt_id: str) -> Hunt | None: ...
    def list_all(self) -> list[Hunt]: ...
    def list_for_session(self, session_id: str) -> list[Hunt]: ...
    def update(self, hunt_id: str, updates: dict[str, Any]) -> None: ...
    def delete(self, hunt_id: str) -> bool: ...


class FindingRepositoryProtocol(Protocol):
    def create(self, finding: Finding) -> None: ...
    def get(self, finding_id: str) -> Finding | None: ...
    def list_for_hunt(self, hunt_id: str) -> list[Finding]: ...
    def list_for_session(self, session_id: str) -> list[Finding]: ...
    def list_filtered(
        self,
        session_id: str | None = None,
        hunt_id: str | None = None,
        severity: str | None = None,
        status: str | None = None,
        agent_source: str | None = None,
        search: str | None = None,
    ) -> list[Finding]: ...
    def update_status(self, finding_id: str, status: FindingStatus) -> None: ...
    def delete(self, finding_id: str) -> bool: ...


class ReportRepositoryProtocol(Protocol):
    def create(self, report: Report) -> None: ...
    def get(self, report_id: str) -> Report | None: ...
    def list_for_session(self, session_id: str) -> list[Report]: ...
    def delete(self, report_id: str) -> bool: ...
