# Generated by Django 5.1.15 on 2026-06-03 05:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('step_type', models.CharField(choices=[('agent_start', 'Agent start'), ('thinking', 'Thinking'), ('tool_call', 'Tool call'), ('tool_result', 'Tool result'), ('agent_complete', 'Agent complete'), ('handoff', 'Handoff'), ('finding', 'Finding'), ('error', 'Error')], max_length=24)),
                ('from_agent', models.CharField(blank=True, default='', max_length=64)),
                ('to_agent', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('input_context', models.JSONField(blank=True, null=True)),
                ('reasoning_text', models.TextField(blank=True, default='')),
                ('output_summary', models.TextField(blank=True, default='')),
                ('structured_output', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_steps', to='hunts.run')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='AgentTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_agent', models.CharField(blank=True, default='', max_length=64)),
                ('to_agent', models.CharField(blank=True, default='', max_length=64)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('edge_type', models.CharField(default='context', max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='hunts.run')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('agent_name', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hunts.run')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='GraphSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('current_node', models.CharField(blank=True, max_length=64, null=True)),
                ('active_nodes', models.JSONField(blank=True, default=list)),
                ('completed_nodes', models.JSONField(blank=True, default=list)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('edges', models.JSONField(blank=True, default=list)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_snapshots', to='hunts.run')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='HuntflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.UUIDField(db_index=True)),
                ('node_type', models.CharField(choices=[('hunt_root', 'Hunt root'), ('agent_task', 'Agent task'), ('reasoning', 'Reasoning'), ('tool_call', 'Tool call'), ('tool_result', 'Tool result'), ('finding', 'Finding'), ('plan_update', 'Plan update'), ('handoff', 'Handoff'), ('error', 'Error')], max_length=24)),
                ('agent_name', models.CharField(blank=True, default='', max_length=64)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='observability.huntflownode')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huntflow_nodes', to='hunts.run')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=64)),
                ('tool_name', models.CharField(db_index=True, max_length=128)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('argv', models.JSONField(blank=True, default=list)),
                ('command_str', models.TextField(blank=True, default='')),
                ('target', models.CharField(blank=True, default='', max_length=512)),
                ('scope', models.CharField(blank=True, default='', max_length=512)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('raw_stdout', models.TextField(blank=True, default='')),
                ('raw_stderr', models.TextField(blank=True, default='')),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('parsed_result', models.JSONField(blank=True, null=True)),
                ('truncated_for_llm', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('unavailable', 'Unavailable')], default='running', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('agent_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='observability.agentstep')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='hunts.run')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=64)),
                ('tool_name', models.CharField(blank=True, default='', max_length=128)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('final_url', models.URLField(blank=True, default='', max_length=2048)),
                ('image', models.ImageField(max_length=512, upload_to='screenshots/%Y/%m/%d/')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bytes', models.IntegerField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, default='', max_length=512)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=512)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='hunts.run')),
                ('tool_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='observability.toolexecution')),
            ],
            options={
                'ordering': ['run', '-taken_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'sequence'], name='observabili_run_id_f6d462_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'agent_name'], name='observabili_run_id_a34ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['run', 'sequence'], name='observabili_run_id_172a94_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_event_run_sequence'),
        ),
        migrations.AddIndex(
            model_name='graphsnapshot',
            index=models.Index(fields=['run', 'sequence'], name='observabili_run_id_676269_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['run', 'sequence'], name='observabili_run_id_fb367a_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tool_name'], name='observabili_tool_na_793eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['run', 'status'], name='observabili_run_id_5e36c1_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['run'], name='observabili_run_id_5125bc_idx'),
        ),
    ]
