# Generated by Django 5.1.15 on 2026-06-03 05:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunts', '0001_initial'),
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='info', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('affected_url', models.CharField(blank=True, default='', max_length=2048)),
                ('evidence', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('agent_source', models.CharField(blank=True, default='', max_length=64)),
                ('tool_used', models.CharField(blank=True, default='', max_length=128)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cve_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('false_positive', 'False positive'), ('accepted_risk', 'Accepted risk'), ('remediated', 'Remediated')], db_index=True, default='new', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='0.0–1.0', null=True)),
                ('exploitability', models.CharField(choices=[('proven', 'Proven'), ('likely', 'Likely'), ('possible', 'Possible'), ('unlikely', 'Unlikely'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('cisa_kev', models.BooleanField(default=False)),
                ('verified_by_agent', models.CharField(blank=True, default='', max_length=64)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='hunts.run')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='hunts.session')),
                ('source_tool_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='observability.toolexecution')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='hunts.target')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', 'severity'], name='findings_fi_run_id_2c0919_idx'), models.Index(fields=['session', 'status'], name='findings_fi_session_16d9b6_idx'), models.Index(fields=['dedup_key'], name='findings_fi_dedup_k_135fff_idx')],
            },
        ),
    ]
