# Generated by Django 5.1.15 on 2026-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='brand_logo_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='workspace',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
