# Generated by Django 5.1.15 on 2026-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='attack_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='run',
            name='attack_status',
            field=models.CharField(default='none', max_length=16),
        ),
    ]
