# Generated by Django 5.1.15 on 2026-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='attack_focus',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
